# Generated by Django 3.1.5 on 2021-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='freetags',
            field=models.ManyToManyField(blank=True, to='todo.Tag'),
        ),
        migrations.AddField(
            model_name='todo',
            name='target',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_todo_tags_+', to='todo.Todo'),
        ),
    ]
